//Creating a class to instantiate plant objects
class Plant {
  constructor(commonName, scientificName, division, plantClass, subclass, order, family, commonFamily, genus, species, imageSrc, imageCite, duration, description, citeYear, url) {
    this.commonName = commonName;
    this.scientificName = scientificName;
    this.classification = {kingdom: 'Plantae', division, plantClass, subclass, order, family, commonFamily, genus, species}
    this.imageSrc = imageSrc;
    this.imageCite = imageCite;
    this.duration = duration;
    this.description = description;
    this.descriptionCite = `Illinois Department of Natural Resources. ${citeYear}. Native Plant Information. Retrieved from ${url}`;
  }
  
  lowerCaseAndRemoveSpace(prop) {
    return this[prop].toLowerCase().split(' ').join('');
  }
}

//Creating the array of plant objects
const plants = [
  new Plant('American bellflower', 'Campanulastrum americanum', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Campanulales', 'Campanulaceae Juss.', 'Bellflower family', 'Campanulastrum Small', 'Campanulastrum americanum', 'https://s7d1.scene7.com/is/image/isp/fygoct2019?qlt=100&wid=900&ts=1689692279748&$ImageComponent$&fit=constrain', null, 'Annual', 'American bellflower is an annual or biennial herb. Its sap is milky. The erect stem may be branched. Leaves are arranged alternately along the stem. Each simple, lance‐shaped leaf is toothed. A single leaf may be six inches long and two inches wide. The five-petaled, pale‐blue flowers are flat and have a lighter ring at the center. The style (part of the female reproductive structures) is very long and curved. Flowers develop in a cluster on a stalk that may be one and one‐half feet long. The fruit is a club‐shaped capsule, about one‐half inch long, containing flat, brown seeds. American bellflower may attain a height of one and one‐half to six feet and may be found throughout Illinois. It grows in woodlands. Flowers are produced from June through November. White‐tailed deer may eat the leaves of this plant.', '2019', 'https://dnr.illinois.gov/education/fygmain/2019/fygoct2019.html'),
  new Plant('American Gromwell', 'Lithospermum latifolium', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Lamiales', 'Boraginaceae Juss.', 'Borage family', 'Lithospermum L.', 'Lithospermum latifolium', 'https://s7d1.scene7.com/is/image/isp/fygapr2019?qlt=100&wid=900&ts=1689613784387&$ImageComponent$&fit=constrain', 'Photo © River Valley Photographic Resources Ltd.', 'Perennial', 'American gromwell grows in rich woodlands statewide. An individual plant may be one and one-half to two and one-half feet tall. Its stems and leaves are covered with small hairs. Flowers develop individually from the leaf axils at the stem tip. Flower color is yellow. The fruit is a nutlet. Long-tongued bees and butterflies are pollinators that can take advantage of the flowers.', '2019', 'https://dnr.illinois.gov/education/fygmain/2019/fygapr2019.html'),
  new Plant('Arrow Arum', 'Peltandra virginica', 'Magnoliophyta', 'Liliopsida', 'Arecidae', 'Arales', 'Araceae Juss.', 'Arum family', 'Peltandra Raf.', 'Peltandra virginica', 'https://s7d1.scene7.com/is/image/isp/fygjul2022?qlt=100&wid=900&ts=1689602028963&$ImageComponent$&fit=constrain', 'Photo © John Hilty', 'Perennial', 'Arrow arum is an aquatic plant that grows in areas of shallow, standing water such as swamps and ditches. It prefers shaded water. It is present in all but the counties of far north central and northwestern Illinois. Its leaves and flower stalks emerge from the water. The plant grows 12-24 inches tall. The leaves are large and arrow-shaped. This species blooms from May through June. The flowers are on a club-shaped structure called a spadix that is surrounded by a leaflike, elongated spathe. The flowers do not have petals or sepals. Fruits are green berries. Flies are attracted by the smell from the flowers and act as pollinators as they feed on the pollen. Waterfowl and some wading birds eat the fruits.', '2022', 'https://dnr.illinois.gov/education/fygmain/2022/fygjul2022.html'),
  new Plant('Azure Aster', 'Symphyotrichum oolentangiense', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Asterales', 'Asteraceae Bercht. & J. Presl', 'Aster family', 'Symphyotrichum Nees', 'Symphyotrichum oolentangiense', 'https://s7d1.scene7.com/is/image/isp/fygnov2018?qlt=100&wid=900&ts=1689692867507&$ImageComponent$&fit=constrain', 'Photo © John Hilty', 'Perennial', 'Azure aster, also known as sky blue aster, is found statewide in prairies, woodland openings and savannas. The plants grow to about three feet tall. Leaves are arranged alternately along the stem. Leaf size and leaf stalk length decrease from the base of the plant to the top. Flowers are present from August through November. Many flower heads are present at the top of the plant. Ray flowers are blue or purple. The flowers are important sources of nectar and pollen for many pollinators. The seeds and leaves also provide food for several species of wildlife.', '2018', 'https://dnr.illinois.gov/education/fygmain/2018/fygnov2018.html'),
  new Plant('Big bluestem', 'Andropogon gerardii', 'Magnoliophyta', 'Liliopsida', 'Commelinidae', 'Cyperales', 'Poaceae Barnhart', 'Grass family', 'Andropogon L.', 'Andropogon gerardii', 'https://s7d1.scene7.com/is/image/isp/bnbigblue?qlt=100&wid=600&ts=1689704368676&$ImageComponent$&fit=constrain', null, 'Perennial', 'You may not consider winter as a time to think about or be impressed by the plants in your garden. Winter gardens can be beautiful, though, and provide important habitat for wildlife. As you plan for your garden this year, consider including some native grasses. Leaving them year round can be a pleasing experience for you, and they require very little maintenance. Native prairie grasses are resistant to cold and drought and are rarely attacked by disease and insects. They are perennials that you can enjoy year after year. Big bluestem is the State Prairie Grass of Illinois. It can grow to a height of six to eight feet. In summer, the leaves are blue-green, thus this plant\'s common name. In fall the leaves turn yellow and bronze. Recommended to be planted far enough from other plants in your garden to give them room to grow and to avoid entanglements with other plants. Since these are tall plants, the back of the garden is a good place for them.', '2008', 'https://dnr.illinois.gov/education/fygmain/2008/fygjan2008.html'), 
  new Plant('Black-eyed Susan', 'Rudbeckia hirta', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Asterales', 'Asteraceae Bercht. & J. Presl', 'Aster family', 'Rudbeckia L.', 'Rudbeckia hirta L.', 'https://s7d1.scene7.com/is/image/isp/bnbesusan?qlt=100&wid=900&ts=1689703803893&$ImageComponent$&fit=constrain', null, 'Annual, Biennial, or Perennial', 'Black-eyed Susan can be found in moist prairies, open woods, pastures, fields, roadsides and savannas in the eastern half of the state. This plant has upright, hairy stems. The simple, lance‐shaped leaves are arranged alternately along the stem. Each hairy leaf has teeth that are widely spaced along the margin. Flowering occurs from June through October. One flower head is produced per plant, although sometimes the plant branches near the base and produces one flower per stem. The flower head contains many small flowers that are of two types: yellow ray flowers (10 to 20 per flower head), about three-fourths inch long; and purple‐brown, tubular flowers in the dome‐shaped center. Some individual plants may have pale‐yellow ray flowers with white tips. Each flower head is about two and one‐half to two and three‐fourths inches wide. This plant may grow to a height of two to three feet. Black-eyed Susan is a short-lived perennial or a biennial (living two years). It readily grows from its seeds, though. The flower heads attract a variety of pollinating insects.', '2017', 'https://dnr.illinois.gov/education/fygmain/2017/fygsep2017.html'),
  new Plant('Blackhaw', 'Viburnum prunifolium', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Dipsacales', 'Caprifoliaceae Juss.', 'Honeysuckle family', 'Viburnum L.', 'Viburnum prunifolium L.', 'https://s7d1.scene7.com/is/image/isp/fygsep2013?qlt=100&wid=900&ts=1689600643119&$ImageComponent$&fit=constrain', null, 'Perennial', 'Blackhaw is a small tree that grows along streams, in woods and on wooded slopes throughout Illinois. It may reach a height of 25 feet with a diameter of six inches. The bark is red-brown with many fissures. Its leaves are simple and arranged oppositely on the stem. A single leaf may be up to three inches long and two inches wide. The leaf edge is very finely toothed. Flowers are produced from April through June. These white flowers form in broad, rounded clusters. The resulting blue-black fruits are fleshy, contain one seed and are readily eaten by wildlife. Fall leaf colors on this small tree are outstanding.', '2013', 'https://dnr.illinois.gov/education/fygmain/2013/fygsep2013.html'),
  new Plant('Blazing star', 'Liatris spicata', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Asterales', 'Asteraceae Bercht. & J. Presl', 'Aster family', 'Liatris Gaertn. ex Schreb.', 'Liatris spicata (L.)', 'https://s7d1.scene7.com/is/image/isp/bnroughbstar?qlt=100&wid=900&ts=1689884463915&$ImageComponent$&fit=constrain', null, 'Perennial', 'There are several species of blazing-star native to Illinois. Their tall spikes of purple flowers can be seen throughout the state from July until late fall. Most commonly associated with prairies, blazing-star varieties are also adapted to savannas, open woods, wet meadows, fens and sandy areas. The plants can grow to a height of about five feet. The stem is unbranched and is covered with a spiral of long, narrow leaves. The plant grows from a corm, an underground stem with scaly leaves that is similar in appearance to a bulb.', '2008', 'https://dnr.illinois.gov/education/fygmain/2008/fygsep2008.html'), 
  new Plant('Bloodroot', 'Sanguinaria canadensis', 'Magnoliophyta', 'Magnoliopsida', 'Magnoliidae', 'Papaverales', 'Papaveraceae Juss.', 'Poppy family', 'Sanguinaria L.', 'Sanguinaria canadensis L.', 'https://s7d1.scene7.com/is/image/isp/fygmar2011?qlt=100&wid=900&ts=1689617320297&$ImageComponent$&fit=constrain', 'Photo © River Valley Photographic Resources, Ltd.', 'Perennial', 'Bloodroot blooms from March through April in rich woodlands throughout Illinois. This plant is a member of the poppy family. When broken, the stem produces an orange-red sap. As the plant’s stem grows underground, its common name is “bloodroot.” The lobed leaf wraps around the flower stalk. The plant grows from six to 12 inches tall and produces a prominent white flower. The rhizomes of this plant slowly spread, and after a few years a small colony of the plants can develop.', '2011', 'https://dnr.illinois.gov/education/fygmain/2011/fygmar2011.html'),
  new Plant('Blue cohosh', 'Caulophyllum thalictroides', 'Magnoliophyta', 'Magnoliopsida', 'Magnoliidae', 'Ranunculales', 'Berberidaceae Juss.', 'Barberry family', 'Caulophyllum Michx.', 'Caulophyllum thalictroides (L.) Michx.', 'https://s7d1.scene7.com/is/image/isp/fygmar2021?qlt=100&wid=600&ts=1689691895765&$ImageComponent$&fit=constrain', 'Photo © River Valley Photographic Resources Ltd., rvprltd.com', 'Perennial', 'Blue cohosh grows statewide in moist woods. Flowers are produced in April and May. The flowers are six-parted and are green-yellow to brown. Its fruits are dark-blue berries. The leaves have seven to nine leaflets. A single plant may be one to three feet tall. The flowers attract pollinators, and the fruits are eaten by wildlife, particularly birds.', '2021', 'https://dnr.illinois.gov/education/fygmain/2021/fygmar2021.html'), 
  new Plant('Blue vervain', 'Verbena hastata', '	Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Lamiales', 'Verbenaceae J. St.-Hil.', 'Verbena family', 'Verbena L.', 'Verbena hastata L.', 'https://s7d1.scene7.com/is/image/isp/fygapr2016?qlt=100&wid=900&ts=1701120339019&$ImageComponent$&fit=constrain', null, 'Perennial', 'Blue vervain is found throughout Illinois in moist woodlands, moist prairies and moist disturbed areas. Flowering occurs from June through October. The blue-to-purple flowers develop on small spikes. Flowers mature first at the bottom of each spike and blooming progresses upward to the tip of the spike. The stem is four-sided and grooved. This plant may reach a height of six feet.  It is a good species for pollinators.', '2016', 'https://dnr.illinois.gov/education/fygmain/2016/fygapr2016.html'),
  new Plant('Bluebells', 'Mertensia virginica', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Lamiales', 'Boraginaceae Juss.', 'Borage family', 'Mertensia Roth', 'Mertensia virginica (L.)', 'https://s7d1.scene7.com/is/image/isp/fygfeb2013?qlt=100&wid=900&ts=1689611832420&$ImageComponent$&fit=constrain', null, 'Perennial', 'Bluebells, also known as Virginia cowslip or mertensia, grow in moist woods and floodplain forests throughout Illinois. Flowers are present from March through June. Flowers are generally blue in color, although white flowers and rose-colored flowers are sometimes present. The flower bud is pink. Like all members of the forget-me-not family, the flowers are produced at the top of the stem, on one side of the stem. Flowers are large and tubular. They hang so that the flower opening faces the ground. The leaves are arranged alternately on the stem. Each leaf is oval and smooth. The plant grows to one to two feet in height.', '2013', 'https://dnr.illinois.gov/education/fygmain/2013/fygfeb2013.html'),
  new Plant('Blue-eyed Mary', 'Collinsia verna', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Scrophulariales', 'Scrophulariaceae Juss.', 'Figwort family', 'Collinsia Nutt.', '	Collinsia verna Nutt.', 'https://s7d1.scene7.com/is/image/isp/fygjun2010?qlt=100&wid=900&ts=1700593692115&$ImageComponent$&fit=constrain', 'Photo © 2009, River Valley Photographic Resources, Ltd., rvprltd.com', 'Annual', 'Blue-eyed Mary grows statewide in Illinois in rich woods. A member of the snapdragon family, this species blooms from April through June. The distinctive flowers have upper lobes that are white and lower lobes that are bright blue. The plant may grow to 24 inches tall. Leaves are lance-shaped and arranged oppositely on the stem.', '2010', 'https://dnr.illinois.gov/education/fygmain/2010/fygjun2010.html'),
  new Plant('Browneyed Susan', 'Rudbeckia triloba L.', 'Magnoliophyta', 'Magnoliopsida', '	Asteridae', 'Asterales', 'Asteraceae Bercht. & J. Presl', 'Aster family', 'Rudbeckia L.', 'Rudbeckia triloba L.', 'https://s7d1.scene7.com/is/image/isp/fygmar2016?qlt=100&wid=900&ts=1701120038975&$ImageComponent$&fit=constrain', null, 'Perennial', 'Brown-eyed Susan is found throughout Illinois in fields, woodlands and along streams. Flowering occurs from June through October. Numerous flowers are produced per plant. The petallike ray flowers are yellow and surround the cone-shaped, dark brown center. Leaves are arranged alternately on the stem. The plant may reach a height of five feet. The flowers of this plant are important to pollinator species.', '2016', 'https://dnr.illinois.gov/education/fygmain/2016/fygmar2016.html'),
  new Plant('Butterfly Milkweed', 'Asclepias tuberosa', 'Magnoliophyta', 'Magnoliopsida', 'Asteridae', 'Gentianales', 'Asclepiadaceae Borkh.', 'Milkweed family', 'Asclepias L.', 'Asclepias tuberosa L.', 'https://s7d1.scene7.com/is/image/isp/bnbutterweed?qlt=100&wid=900&ts=1689704438410&$ImageComponent$&fit=constrain', null, 'Perennial', 'The flowers of butterfly-weed can be seen in the woods, prairies and savannas of Illinois from May through September. It grows particularly well in sandy soil. Typically the flowers are orange, but they can also be shades of yellow and red. The stems are hairy with leaves generally alternate, but leaves may be opposite on the upper part of the stem. The plant grows to a height of two to three feet. The sap of this species is clear, unlike the white sap of other milkweeds. The seed pods are five to six inches in length. As its common name indicates, the plant attracts butterflies as a food source for both adults and larvae.', '2013', 'https://dnr.illinois.gov/education/fygmain/2013/fygjul2013.html'),
  new Plant()];

//Creating IDs for all the plants
plants.forEach((plant, index) => plant.id = index + 1);

module.exports = plants;